### ISSUE TITLE
Can't create repository

### ISSUE THREAD

**Issue by frakman1** [ikatson/docker-reviewboard#51]
I am trying to add a regular git repository hosted in my network but keep getting errors.

When I go to `http://<myip>:8000/admin/db/scmtools/repository/add/` and try to add a repository, the only option I am allowed to select for Repository Hosting is 

![image](https://user-images.githubusercontent.com/5826484/81524249-6e79cf00-931e-11ea-86fb-8328caa4b452.png)

Everything else requires a PowerPack. e.g.

![image](https://user-images.githubusercontent.com/5826484/81524262-7a659100-931e-11ea-9948-ac45f710c0da.png)

In that case, the next field, Repository Information only has two options:

![image](https://user-images.githubusercontent.com/5826484/81524310-a6811200-931e-11ea-95b8-37c1f43beed7.png)

Both of them give me errors.

**Comment by nejch** [comment]
I'm getting something similar and I think maybe the current builds (from dockerhub) are broken? If you inspect the container logs do you get things like:

```
ERROR:root:Unable to load repository hosting service github: (Django 1.6.11 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('Django>=1.11.0'), set(['django-braces'])).
Traceback (most recent call last):
  File "/opt/venv/local/lib/python2.7/site-packages/djblets/registries/registry.py", line 364, in get_defaults
    yield self.process_value_from_entry_point(ep)
  File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/hostingsvcs/service.py", line 1207, in process_value_from_entry_point
    cls = entry_point.load()
  File "/opt/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/opt/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (Django 1.6.11 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('Django>=1.11.0'), set(['django-braces']))
```

**Comment by ikatson** [comment]
Hi everyone, thanks for the bug reports, I'm pretty busy these days, will appreciate if someone tries to take a look and how to fix it. I'll try to fix this when I have some spare cycles, but not sure when

**Comment by nejch** [comment]
I think all the version conflicts are an upstream issue that was fixed after 3.0.14, see https://github.com/reviewboard/reviewboard/commit/48eee0bea75f025e7fcecf1219359260ea26ab3e. I'll try to bump the version locally to 3.0.17 and see if that helps - it might be enough.

**Comment by frakman1** [comment]
@nejch I'm glad it's not just me. Actually, I see a different slew of repeated errors:

```bash
ERROR:root:Unable to load repository hosting service fedorahosted: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit'])).

Traceback (most recent call last):
File "/opt/venv/local/lib/python2.7/site-packages/djblets/registries/registry.py", line 364, in get_defaults
yield self.process_value_from_entry_point(ep)
File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/hostingsvcs/service.py", line 1291, in process_value_from_entry_point
cls = entry_point.load()
File "/opt/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2323, in load
self.require(*args, **kwargs)
File "/opt/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in require
items = working_set.resolve(reqs, env, installer, extras=self.extras)
File "/opt/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit']))
```

**Comment by frakman1** [comment]
@nejch How does one bump the version of reviewboard? Is that somewhere in `docker-compose.yml` or `Dockerfile`?

**Comment by nejch** [comment]
Yeah, that still seems related, as its the same packages as described in the upstream commit above. Yes, currently you can change it in the Dockerfile:

https://github.com/ikatson/docker-reviewboard/blob/216770a8beffcf05b2b71a79f63f01d8a0482481/Dockerfile#L4

**Comment by frakman1** [comment]
I'm actually running `docker-compose up`. Will the Dockerfile change work for me or is there an equivalent change in `docker-compose.yml`?

**Comment by frakman1** [comment]
Well I am using version 3.0.17 and still have this error:

![image](https://user-images.githubusercontent.com/5826484/81887381-f6edaf00-956c-11ea-8815-fe84d88c72bd.png)

**Comment by nejch** [comment]
I see you got it :) Ok, I tried 3.0.17 and I'm also still having issues. Maybe there needs to be some more restrictions in version ranges for some of the dependencies, but I'll also try a fresh install on another host just to check whether it's a consistent issue.

**Comment by frakman1** [comment]
I'm not sure how I ended up with version 3.0.17. Does just re-running `docker-compose up` just get the latest version? Where does it get specified ultimately?

**Comment by frakman1** [comment]
@ikatson Why did you close this issue? 
#52 doesn't fix this. It makes it worse. I get multiple components complain about oath incorrect version. I did a `git pull` and `docker-compose up` 

```
ERROR:root:Unable to load repository hosting service bugzilla: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit'])).
ERROR:root:Unable to load repository hosting service redmine: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit'])).
ERROR:root:Unable to load repository hosting service versionone: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit'])).
ERROR:root:Unable to load repository hosting service kiln: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit'])).
ERROR:root:Unable to load repository hosting service fogbugz: (oauthlib 3.1.0 (/opt/venv/lib/python2.7/site-packages), Requirement.parse('oauthlib==1.0.1'), set(['django-oauth-toolkit'])).
```

**Comment by ikatson** [comment]
@frakman1 sorry, it got closed automatically when I merged that PR, reopened

**Comment by ikatson** [comment]
Ok I think I fixed it in https://github.com/ikatson/docker-reviewboard/commit/e4ec1472d9cf64335e44ab98e1916a0b42aa69d3

This actually was the oauthlib error, but this time I had the chance to validate it myself :)
Also pinned django-storages to 1.1.8, which is recommended by reviewboard installation instructions, maybe that was causing an issue too.

In only worked for me when I did "make clean" and then "make run". If you run some other way, I guess you need to re-run database migrations, or some reviewboard tool to sync.

**Comment by frakman1** [comment]
This is still not working @ikatson . Please re-open.

I did a `git pull`, `make clean` and `make run`  and I still can't login. I get this screen:

![image](https://user-images.githubusercontent.com/5826484/83951519-e8a75180-a7ff-11ea-87fe-9aa6c25d1486.png)

`docker-compose logs` shows:
```
reviewboard_1  | [pid: 577|app: 0|req: 4/59] 192.168.86.60 () {42 vars in 4009 bytes} [Sat Jun  6 18:10:41 2020] GET /account/login/?next=/r/ => generated 2529 bytes in 19 msecs (HTTP/1.1 200) 11 headers in 475 bytes (1 switches on core 0)
reviewboard_1  | [pid: 578|app: -1|req: -1/60] 192.168.86.60 () {40 vars in 4021 bytes} [Sat Jun  6 18:10:41 2020] GET /static/lib/js/jquery-1.11.1.min.8101d596b2b8.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 0 headers in 29 bytes (0 switches on core 0)
reviewboard_1  | [pid: 579|app: -1|req: -1/61] 192.168.86.60 () {40 vars in 4035 bytes} [Sat Jun  6 18:10:41 2020] GET /static/lib/js/jquery-migrate-1.2.1.min.eb05d8d73b5b.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 0 headers in 29 bytes (0 switches on core 0)
reviewboard_1  | [pid: 571|app: 0|req: 2/62] 192.168.86.60 () {38 vars in 3886 bytes} [Sat Jun  6 18:10:41 2020] GET /jsi18n/ => generated 773 bytes in 4 msecs (HTTP/1.1 200) 7 headers in 231 bytes (1 switches on core 0)
reviewboard_1  | [pid: 574|app: -1|req: -1/63] 192.168.86.60 () {40 vars in 4039 bytes} [Sat Jun  6 18:10:41 2020] GET /static/rb/images/logo.cc81d3ae01b2.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 0 headers in 29 bytes (0 switches on core 0)
reviewboard_1  | invalid request block size: 4189 (max 4096)...skip
reviewboard_1  | [uwsgi-http key: tower:8000 client_addr: 192.168.86.60 client_port: 39925] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 646]
```

**Comment by frakman1** [comment]
I was able to get around this by increasing the buffer-size in `uwsgi.ini` file:

`buffer-size=8192`
